### ISSUE TITLE
Why is the output in object format and not array format?

### ISSUE THREAD

**Issue by ooker777** [tinyCodes1/pdftext#1]
Great work, thanks. I just wonder why you decide to use the object format for the output, not the array format?

**Comment by tinyCodes1** [comment]
Not necessarily, for adding new features easily in future, in case.

**Comment by ooker777** [comment]
Can you give an example for the advantage? Or a pointer to that?

**Comment by tinyCodes1** [comment]
yep ... assuming the returned object is rObj,

then additional functions be like ,

rObj.largerTexts()   // to get all titles
rObj.boldTexts()     // to get all bold texts
rObj.links()         // to get all links
rObj.firstLines()    // to get all non empty first lines from pdf-pages
 ... and so on
 

 I'm not working on it. but its easily possible to add such and more features.

**Comment by ooker777** [comment]
Ah I see. It has the advantage of having methods. Thanks for the explanation.
